#!/usr/bin/env bash
# sed regression probe (pre-existing non-brace forms). usage: sed-regress-probe.sh <sed-binary> <outdir>
set -u
SEDBIN="$1"
OUT="$2"
mkdir -p "$OUT"
printf "alpha\nbravo\ncarlos\ndelta\n" > "$OUT/in.txt"
printf "rdata\n" > "$OUT/rfile.txt"
run() {
  local id="$1"; shift
  "$SEDBIN" "$@" "$OUT/in.txt" > "$OUT/$id.out" 2> "$OUT/$id.err"
  printf "E=%s\n" "$?" > "$OUT/$id.exit"
}
run r01 -e "s/a/X/"
run r02 -e "s/a/X/g"
run r03 -e "s|a|X|g"
run r04 -e "s/a/X/2"
run r05 -e "s/a/X/ip"
run r06 -e "s/a/\1/"
run r07 -e "s/a/&X/"
run r08 -e "s/a/b/g; s/c/d/"
run r09 -e "s/\(a\)/[\1]/"
run r10 -e "s/a/\Lb\E/"
run r11 -e "s/  */ /g"
run r12 -e "N; s/\n/ /"
run r13 -e "s/\$/ END/"
run r14 -e "s/^/START /"
run r15 -e "s/[aeiou]/X/g"
run r16 -e "s/[^aeiou]/X/g"
run r17 -e "y/abc/xyz/"
run r18 -e "1,2 s/a/X/"
run r19 -e "3 s/a/X/"
run r20 -e "\$ s/a/X/"
run r21 -e "/b/ s/a/X/"
run r22 -e "/z/ s/a/X/"
run r23 -e "! s/a/X/"
run r24 -e "2! s/a/X/"
run r25 -e "0,/c/ s/a/X/"
run r26 -e "2,+1 s/a/X/"
run r27 -e "1,~2 s/a/X/"
run r28 -e "0,/b/ s/a/X/g; /b/ d"
run r29 -e "d"
run r30 -e "1d"
run r31 -e "2,\$d"
run r32 -e "h; G; g"
run r33 -e "N; P; P"
run r34 -e "=; N; ="
run r35 -e "l"
run r36 -e "l5"
run r37 -e "x; s/a/X/; x"
run r38 -e "s/a/X/p"
run r39 -e "b label; label"
run r40 -e "/b/ b"
run r41 -e "q"
run r42 -e "2q"
run r43 -e "a\appended"
run r44 -e "i\inserted"
run r45 -e "c\replaced"
run r46 -e "s/a/X/# trailing comment"
run r47 -e "p; # comment; d"
run r48 -e "s/a/X/" -e "s/b/Y/"
run r49 -e "s/\(a\)/[\1]/" -e "p"
run r50 -E "s/(b)avo/\1/"
run r51 --regexp-type=extended "s/(b)avo/\1/"
run r52 --posix "s/[[:alpha:]]+/X/"
run r53 -n "p"
run r54 -n "p;"
run r55 -n "p;;"
run r56 -n "  p  "
run r57 -n "p   "
run r61 -n -z "N; s/\0/ /"
run r62 -n "h"
run r63 -n "H; g; G; g; G"
printf "s/a/X/\n p\n" > "$OUT/r58.sed"
run r58 -n -f "$OUT/r58.sed"
printf "s/a/X/# comment\ns/b/Y/\n" > "$OUT/r59.sed"
run r59 -n -f "$OUT/r59.sed"
printf "#n\n" > "$OUT/r60.sed"
run r60 -f "$OUT/r60.sed"
echo REGRESS_DONE
